name: Deploy to Lightsail

on:
  workflow_dispatch:
    inputs:
      instanceName:
        description: 'Name of AWS Lightsail instance'     
        required: true
        default: 'SteamServer'
      steamServerName:
        description: 'Name of AWS Lightsail instance'     
        required: true
        default: '#1 Casual Coop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install find replace
        run: |
          curl -LJO https://github.com/joshuaschlichting/findreplace/releases/download/v0.0.1/findreplace_linux_amd64
          chmod +x findreplace_linux_amd64
          sudo mv findreplace_linux_amd64 /usr/local/bin/findreplace

      - name: Plug game server name into lightsail startup script
        run: findreplace -find "$1" -replace "${{ github.event.inputs.steamServerName }}" -path lightsail_startup.sh


      - name: Deploy Lightsail server
        run: ./deploy_lightsail.sh ${{ github.event.inputs.instanceName }} "${{ github.event.inputs.steamServerName }}"
